---
version: "3"

vars:
  RUST_PYTHON: /opt/exec-wrapper/bin/rustpython

tasks:

  list:
    desc: List available tasks
    cmds:
      - cmd: 'task --list'

  test-exec-wrapper-deno:
    desc: Test the exec wrapper for Deno
    vars:
      EXEC_LOG_LEVEL: debug
      EXEC_BIN_DIR: /opt/exec-wrapper/bin
      #EXEC_BIN_DIR:
      #  sh: |
      #    echo ${HOME}/projects/niceguyit/pimp-my-tactical/scripts/tmp
      EXEC_BINARY: deno
      EXEC_SCRIPT_URL: https://raw.githubusercontent.com/NiceGuyIT/pimp-my-tactical/main/scripts/wrapper/hello-world.ts
    cmds:
      - cmd: |
          export EXEC_LOG_LEVEL='{{.EXEC_LOG_LEVEL}}'
          export EXEC_BIN_DIR='{{.EXEC_BIN_DIR}}'
          export EXEC_BINARY='{{.EXEC_BINARY}}'
          export EXEC_SCRIPT_URL='{{.EXEC_SCRIPT_URL}}'
          {{.RUST_PYTHON}} scripts/all-exec-wrapper.py

  test-exec-wrapper-nushell:
    desc: Test the exec wrapper for Nu shell
    vars:
      EXEC_LOG_LEVEL: debug
      EXEC_BIN_DIR: /opt/exec-wrapper/bin
      #EXEC_BIN_DIR:
      #  sh: |
      #    echo ${HOME}/projects/niceguyit/pimp-my-tactical/scripts/tmp
      EXEC_BINARY: nushell
      EXEC_SCRIPT_URL: https://raw.githubusercontent.com/NiceGuyIT/pimp-my-tactical/main/scripts/wrapper/hello-world.nu
    cmds:
      - cmd: |
          export EXEC_LOG_LEVEL='{{.EXEC_LOG_LEVEL}}'
          export EXEC_BIN_DIR='{{.EXEC_BIN_DIR}}'
          export EXEC_BINARY='{{.EXEC_BINARY}}'
          export EXEC_SCRIPT_URL='{{.EXEC_SCRIPT_URL}}'
          {{.RUST_PYTHON}} scripts/all-exec-wrapper.py

  test-exec-wrapper-rustpython:
    desc: Test the exec wrapper for RustPython
    vars:
      EXEC_LOG_LEVEL: debug
      EXEC_BIN_DIR: /opt/exec-wrapper/bin
      #EXEC_BIN_DIR:
      #  sh: |
      #    echo ${HOME}/projects/niceguyit/pimp-my-tactical/scripts/tmp
      EXEC_BINARY: rustpython
      EXEC_SCRIPT_URL: https://raw.githubusercontent.com/NiceGuyIT/pimp-my-tactical/main/scripts/wrapper/hello-world.py
    cmds:
      - cmd: |
          export EXEC_LOG_LEVEL='{{.EXEC_LOG_LEVEL}}'
          export EXEC_BIN_DIR='{{.EXEC_BIN_DIR}}'
          export EXEC_BINARY='{{.EXEC_BINARY}}'
          export EXEC_SCRIPT_URL='{{.EXEC_SCRIPT_URL}}'
          {{.RUST_PYTHON}} scripts/all-exec-wrapper.py

  dev-explorer-bookmarks:
    desc: Develop the Explorer Bookmarks script
    env:
      EB_LOG_LEVEL: DEBUG
    cmds:
      # .USER_WORKING_DIR returns the Windows path which does not work in MSYS.
      - cmd: |
          [[ ! -d "wrapper" ]] && echo "This needs to be run in the wrapper directory"
          deno run \
            --allow-read \
            --allow-write \
            --allow-run \
            --allow-sys \
            --allow-env \
            wrapper/explorer-bookmarks.ts task

  watch-explorer-bookmarks:
    desc: Develop the Explorer Bookmarks script using deno watch mode
    cmds:
      - cmd: |
          cd {{ quote .USER_WORKING_DIR }}
          deno run \
            --watch \
            --allow-read \
            --allow-write \
            --allow-run \
            --allow-sys \
            --allow-env \
            explorer-bookmarks.ts
