---
version: "3"

tasks:

  list:
    desc: List available tasks
    cmds:
      - cmd: 'task --list'

  test-exec-wrapper-deno:
    desc: Test the exec wrapper for Deno
    vars:
      EXEC_LOG_LEVEL: debug
      EXEC_BIN_DIR:
        sh: |
          echo ${HOME}/projects/niceguyit/pimp-my-tactical/scripts/tmp
      EXEC_BINARY: deno
      EXEC_SCRIPT_URL: https://raw.githubusercontent.com/NiceGuyIT/pimp-my-tactical/main/scripts/wrapper/hello-world.ts
    cmds:
      - cmd: |
          export EXEC_LOG_LEVEL='{{.EXEC_LOG_LEVEL}}'
          export EXEC_BIN_DIR='{{.EXEC_BIN_DIR}}'
          export EXEC_BINARY='{{.EXEC_BINARY}}'
          export EXEC_SCRIPT_URL='{{.EXEC_SCRIPT_URL}}'
          python3.6 scripts/all-exec-wrapper.py

  test-exec-wrapper-nushell:
    desc: Test the exec wrapper for Nu shell
    vars:
      EXEC_LOG_LEVEL: debug
      EXEC_BIN_DIR:
        sh: |
          echo ${HOME}/projects/niceguyit/pimp-my-tactical/scripts/tmp
      EXEC_BINARY: nushell
      EXEC_SCRIPT_URL: https://raw.githubusercontent.com/NiceGuyIT/pimp-my-tactical/main/scripts/wrapper/hello-world.nu
    cmds:
      - cmd: |
          export EXEC_LOG_LEVEL='{{.EXEC_LOG_LEVEL}}'
          export EXEC_BIN_DIR='{{.EXEC_BIN_DIR}}'
          export EXEC_BINARY='{{.EXEC_BINARY}}'
          export EXEC_SCRIPT_URL='{{.EXEC_SCRIPT_URL}}'
          python3.6 scripts/all-exec-wrapper.py

  test-exec-wrapper-rustpython:
    desc: Test the exec wrapper for RustPython
    vars:
      EXEC_LOG_LEVEL: debug
      EXEC_BIN_DIR:
        sh: |
          echo ${HOME}/projects/niceguyit/pimp-my-tactical/scripts/tmp
      EXEC_BINARY: rustpython
      EXEC_SCRIPT_URL: https://raw.githubusercontent.com/NiceGuyIT/pimp-my-tactical/main/scripts/wrapper/hello-world.py
    cmds:
      - cmd: |
          export EXEC_LOG_LEVEL='{{.EXEC_LOG_LEVEL}}'
          export EXEC_BIN_DIR='{{.EXEC_BIN_DIR}}'
          export EXEC_BINARY='{{.EXEC_BINARY}}'
          export EXEC_SCRIPT_URL='{{.EXEC_SCRIPT_URL}}'
          python3.6 scripts/all-exec-wrapper.py
